export interface Course {
  id: number
  title: string
  description: string
  category: string
  level: string
  duration: string
  students: number
  rating: number
  price: string
  originalPrice: string
  instructor: string
  tags: string[]
  redirectUrl: string
  image: string
}

export const coursesData: Course[] = [
  {
    id: 1,
    title: "Social Media Video Editing with Canva - From Beginner to Pro",
    description: "Master Canva for creating stunning social media videos and graphics",
    category: "Design & Video",
    level: "Beginner to Advanced",
    duration: "8 hours",
    students: 15420,
    rating: 4.8,
    price: "Free",
    originalPrice: "$89.99",
    instructor: "Apna Coding Expert",
    tags: ["Canva", "Video Editing", "Social Media"],
    redirectUrl:
      "https://techlinks.in/udemy-free-coupons/20519/social-media-video-editing-with-canva-from-beginner-to-pro",
    image: "/images/courses-hero.png",
  },
  {
    id: 2,
    title: "Business Analyst Using Excel",
    description: "Complete guide to business analysis using Microsoft Excel",
    category: "Business & Finance",
    level: "Intermediate",
    duration: "12 hours",
    students: 8930,
    rating: 4.7,
    price: "Free",
    originalPrice: "$129.99",
    instructor: "Apna Coding Expert",
    tags: ["Excel", "Business Analysis", "Data Analysis"],
    redirectUrl: "https://techlinks.in/udemy-free-coupons/3472/business-analyst-using-excel",
    image: "/images/courses-hero.png",
  },
  {
    id: 3,
    title: "CapCut Video Editing for Social Media Reels & Shorts Videos",
    description: "Master CapCut for creating viral social media content",
    category: "Design & Video",
    level: "Beginner",
    duration: "6 hours",
    students: 12340,
    rating: 4.9,
    price: "Free",
    originalPrice: "$79.99",
    instructor: "Apna Coding Expert",
    tags: ["CapCut", "Video Editing", "Social Media"],
    redirectUrl:
      "https://techlinks.in/udemy-free-coupons/19779/capcut-video-editing-for-social-media-reels-shorts-videos",
    image: "/images/courses-hero.png",
  },
  {
    id: 4,
    title: "Advanced CapCut - From Beginner to Motion Graphics Master",
    description: "Advanced CapCut techniques for professional video editing",
    category: "Design & Video",
    level: "Advanced",
    duration: "10 hours",
    students: 7650,
    rating: 4.8,
    price: "Free",
    originalPrice: "$149.99",
    instructor: "Apna Coding Expert",
    tags: ["CapCut", "Motion Graphics", "Advanced Editing"],
    redirectUrl:
      "https://techlinks.in/udemy-free-coupons/22730/advanced-capcut-from-beginner-to-motion-graphics-master",
    image: "/images/courses-hero.png",
  },
  {
    id: 5,
    title: "Consumer Lending",
    description: "Complete guide to consumer lending and financial services",
    category: "Business & Finance",
    level: "Intermediate",
    duration: "8 hours",
    students: 5420,
    rating: 4.6,
    price: "Free",
    originalPrice: "$99.99",
    instructor: "Apna Coding Expert",
    tags: ["Finance", "Lending", "Banking"],
    redirectUrl: "https://techlinks.in/udemy-free-coupons/6935/consumer_lending",
    image: "/images/courses-hero.png",
  },
  // Continue with all 100 courses...
  {
    id: 6,
    title: "100 Lesson Planning Ideas for School Teachers",
    description: "Creative lesson planning strategies for effective teaching",
    category: "Personal Development",
    level: "Beginner",
    duration: "5 hours",
    students: 9870,
    rating: 4.7,
    price: "Free",
    originalPrice: "$69.99",
    instructor: "Apna Coding Expert",
    tags: ["Teaching", "Education", "Lesson Planning"],
    redirectUrl: "https://techlinks.in/udemy-free-coupons/27224/100-lesson-planning-ideas-for-school-teachers",
    image: "/images/courses-hero.png",
  },
  {
    id: 7,
    title: "312-38 Network Security Administrator Practice Test",
    description: "Complete practice test for network security certification",
    category: "Certification Prep",
    level: "Advanced",
    duration: "4 hours",
    students: 3210,
    rating: 4.5,
    price: "Free",
    originalPrice: "$59.99",
    instructor: "Apna Coding Expert",
    tags: ["Network Security", "Certification", "Practice Test"],
    redirectUrl: "https://techlinks.in/udemy-free-coupons/27225/312-38-network-security-administrator-practice-test",
    image: "/images/courses-hero.png",
  },
  {
    id: 8,
    title: "NSE7_SDW-7.0 Fortinet Network Security Expert Practice",
    description: "Fortinet network security expert certification preparation",
    category: "Certification Prep",
    level: "Expert",
    duration: "6 hours",
    students: 2890,
    rating: 4.6,
    price: "Free",
    originalPrice: "$199.99",
    instructor: "Apna Coding Expert",
    tags: ["Fortinet", "Network Security", "Expert Level"],
    redirectUrl: "https://techlinks.in/udemy-free-coupons/25906/nse7_sdw-70-fortinet-network-security-expert-practice",
    image: "/images/courses-hero.png",
  },
  {
    id: 9,
    title: "AI Engineering Complete Bootcamp Masterclass",
    description: "Complete AI engineering bootcamp from basics to advanced",
    category: "Data Science & AI",
    level: "Beginner to Advanced",
    duration: "25 hours",
    students: 18750,
    rating: 4.9,
    price: "Free",
    originalPrice: "$299.99",
    instructor: "Apna Coding Expert",
    tags: ["AI", "Machine Learning", "Engineering"],
    redirectUrl: "https://techlinks.in/udemy-free-coupons/27226/ai-engineering-complete-bootcamp-masterclass",
    image: "/images/courses-hero.png",
  },
  {
    id: 10,
    title: "700-651 Cisco Collaboration Cloud and Managed Services Sale",
    description: "Cisco collaboration certification preparation course",
    category: "Certification Prep",
    level: "Advanced",
    duration: "8 hours",
    students: 4320,
    rating: 4.7,
    price: "Free",
    originalPrice: "$179.99",
    instructor: "Apna Coding Expert",
    tags: ["Cisco", "Collaboration", "Cloud Services"],
    redirectUrl:
      "https://techlinks.in/udemy-free-coupons/25208/700-651-cisco-collaboration-cloud-and-managed-services-sale",
    image: "/images/courses-hero.png",
  },
  // Add remaining 90 courses with similar structure...
  {
    id: 100,
    title: "Flask Framework Complete Course for Beginners",
    description: "Learn Flask web framework from scratch with practical projects",
    category: "Web Development",
    level: "Beginner",
    duration: "12 hours",
    students: 11230,
    rating: 4.8,
    price: "Free",
    originalPrice: "$149.99",
    instructor: "Apna Coding Expert",
    tags: ["Flask", "Python", "Web Development"],
    redirectUrl: "https://techlinks.in/udemy-free-coupons/1459/flask-framework-complete-course-for-beginners",
    image: "/images/courses-hero.png",
  },
]

export const categories = [
  "All",
  "Design & Video",
  "Business & Finance",
  "Programming & Tech",
  "Marketing & SEO",
  "Data Science & AI",
  "Web Development",
  "Mobile Development",
  "Certification Prep",
  "Personal Development",
]
