-- Insert sample users (including admin)
INSERT INTO users (id, email, full_name, role, bio, skills, github_url, linkedin_url) VALUES
('550e8400-e29b-41d4-a716-446655440000', 'sonishriyash@gmail.com', 'Shriyash Soni', 'admin', 'Founder & CEO of Apna Coding. Passionate about technology and education.', ARRAY['JavaScript', 'React', 'Node.js', 'Python', 'Leadership'], 'https://github.com/shriyashsoni', 'https://linkedin.com/in/shriyashsoni'),
('550e8400-e29b-41d4-a716-446655440001', 'user@example.com', 'John Doe', 'user', 'Full-stack developer with 3 years of experience.', ARRAY['React', 'Node.js', 'MongoDB'], 'https://github.com/johndoe', 'https://linkedin.com/in/johndoe'),
('550e8400-e29b-41d4-a716-446655440002', 'jane@example.com', 'Jane Smith', 'user', 'Frontend developer passionate about UI/UX.', ARRAY['React', 'Vue.js', 'CSS', 'Figma'], 'https://github.com/janesmith', 'https://linkedin.com/in/janesmith');

-- Insert sample courses
INSERT INTO courses (title, description, image_url, price, duration, level, technologies, instructor, students_count, rating, status, redirect_url, category, original_price, tags) VALUES
('Complete Web Development Bootcamp', 'Learn full-stack web development from scratch with HTML, CSS, JavaScript, React, Node.js, and MongoDB.', '/images/courses-hero.png', 99.99, '12 weeks', 'Beginner', ARRAY['HTML', 'CSS', 'JavaScript', 'React', 'Node.js', 'MongoDB'], 'Shriyash Soni', 1250, 4.8, 'active', 'https://apnacoding.com/courses/web-development', 'Web Development', '$199', ARRAY['fullstack', 'beginner-friendly', 'project-based']),
('Advanced React & Next.js', 'Master advanced React concepts and build production-ready applications with Next.js.', '/images/courses-hero.png', 149.99, '8 weeks', 'Advanced', ARRAY['React', 'Next.js', 'TypeScript', 'Tailwind CSS'], 'Shriyash Soni', 850, 4.9, 'active', 'https://apnacoding.com/courses/react-nextjs', 'Frontend Development', '$299', ARRAY['react', 'nextjs', 'advanced']),
('Python for Data Science', 'Learn Python programming and data science libraries like Pandas, NumPy, and Matplotlib.', '/images/courses-hero.png', 79.99, '10 weeks', 'Intermediate', ARRAY['Python', 'Pandas', 'NumPy', 'Matplotlib', 'Jupyter'], 'Dr. Priya Sharma', 950, 4.7, 'active', 'https://apnacoding.com/courses/python-data-science', 'Data Science', '$159', ARRAY['python', 'data-science', 'analytics']),
('Mobile App Development with React Native', 'Build cross-platform mobile apps using React Native and Expo.', '/images/courses-hero.png', 129.99, '10 weeks', 'Intermediate', ARRAY['React Native', 'Expo', 'JavaScript', 'Firebase'], 'Rahul Kumar', 650, 4.6, 'active', 'https://apnacoding.com/courses/react-native', 'Mobile Development', '$249', ARRAY['mobile', 'react-native', 'cross-platform']),
('DevOps & Cloud Computing', 'Learn Docker, Kubernetes, AWS, and CI/CD pipelines for modern application deployment.', '/images/courses-hero.png', 199.99, '14 weeks', 'Advanced', ARRAY['Docker', 'Kubernetes', 'AWS', 'Jenkins', 'Terraform'], 'Amit Patel', 420, 4.8, 'active', 'https://apnacoding.com/courses/devops-cloud', 'DevOps', '$399', ARRAY['devops', 'cloud', 'aws', 'docker']);

-- Insert sample hackathons
INSERT INTO hackathons (title, description, image_url, start_date, end_date, registration_deadline, location, prize_pool, participants_count, status, registration_open, technologies, registration_link, whatsapp_link, organizer, partnerships, featured, mode, difficulty, max_team_size) VALUES
('BNB AI Hack | Bombay Edition', 'Build the future of AI with BNB Chain. Create innovative AI-powered dApps and win amazing prizes!', '/images/bnb-hack-mumbai.jpeg', '2024-03-15', '2024-03-17', '2024-03-10', 'Mumbai, India', '$100K+', 2500, 'upcoming', true, ARRAY['AI', 'Blockchain', 'BNB Chain', 'Solidity', 'Python'], 'https://bnbhack.devpost.com', 'https://chat.whatsapp.com/bnbhack', 'BNB Chain', ARRAY['BNB Chain', 'Devpost', 'Apna Coding'], true, 'offline', 'intermediate', 4),
('ETH India 2025', 'India''s largest Ethereum hackathon. Build decentralized applications and shape the future of Web3.', '/images/eth-india-2025.jpeg', '2024-04-20', '2024-04-22', '2024-04-15', 'Bangalore, India', '$200K+', 3000, 'upcoming', true, ARRAY['Ethereum', 'Solidity', 'Web3', 'DeFi', 'NFT'], 'https://ethindia.co', 'https://chat.whatsapp.com/ethindia', 'ETH India', ARRAY['Ethereum Foundation', 'Polygon', 'Chainlink'], true, 'offline', 'advanced', 5),
('Google Solution Challenge 2024', 'Solve real-world problems using Google technologies and make a positive impact on society.', '/images/google-solution-challenge.jpeg', '2024-02-01', '2024-05-31', '2024-04-30', 'Global (Online)', '$100K+', 5000, 'ongoing', true, ARRAY['Flutter', 'Firebase', 'Google Cloud', 'TensorFlow', 'Android'], 'https://developers.google.com/solution-challenge', 'https://chat.whatsapp.com/googlesolution', 'Google', ARRAY['Google', 'Google Cloud', 'Firebase'], true, 'online', 'beginner', 4),
('Smart India Hackathon 2024', 'India''s biggest hackathon for students to solve pressing problems faced by our country.', '/images/smart-india-hackathon.jpeg', '2024-08-15', '2024-08-17', '2024-07-30', 'Multiple Cities, India', '$50K+', 10000, 'upcoming', true, ARRAY['AI', 'IoT', 'Blockchain', 'Mobile Apps', 'Web Development'], 'https://sih.gov.in', 'https://chat.whatsapp.com/sih2024', 'Government of India', ARRAY['AICTE', 'Ministry of Education'], false, 'hybrid', 'beginner', 6),
('NASA Space Apps Challenge', 'Join the world''s largest global hackathon focused on space exploration and Earth science.', '/images/nasa-space-apps.jpeg', '2024-10-05', '2024-10-06', '2024-09-30', 'Global (Multiple Locations)', '$50K+', 25000, 'upcoming', true, ARRAY['Python', 'Data Science', 'Machine Learning', 'APIs', 'Visualization'], 'https://spaceappschallenge.org', 'https://chat.whatsapp.com/nasaspaceapps', 'NASA', ARRAY['NASA', 'ESA', 'Space Agencies'], false, 'hybrid', 'intermediate', 6);

-- Insert sample jobs
INSERT INTO jobs (title, company, description, location, type, salary, experience, technologies, company_logo, status, posted_date, application_deadline, apply_link, requirements) VALUES
('Full Stack Developer', 'TechCorp Solutions', 'We are looking for a talented Full Stack Developer to join our growing team. You will be responsible for developing and maintaining web applications using modern technologies.', 'Mumbai, India', 'Full-time', '$60,000 - $80,000', '2-4 years', ARRAY['React', 'Node.js', 'MongoDB', 'Express.js', 'JavaScript'], '/placeholder-logo.png', 'active', '2024-01-15', '2024-02-15', 'https://techcorp.com/careers/fullstack', ARRAY['Bachelor''s degree in Computer Science', 'Experience with React and Node.js', 'Strong problem-solving skills', 'Good communication skills']),
('Frontend Developer', 'StartupXYZ', 'Join our innovative startup as a Frontend Developer. Work on cutting-edge projects and help shape the future of our product.', 'Bangalore, India', 'Full-time', '$45,000 - $65,000', '1-3 years', ARRAY['React', 'TypeScript', 'Tailwind CSS', 'Next.js'], '/placeholder-logo.png', 'active', '2024-01-20', '2024-02-20', 'https://startupxyz.com/jobs/frontend', ARRAY['Experience with React and TypeScript', 'Knowledge of modern CSS frameworks', 'Understanding of responsive design', 'Portfolio of previous work']),
('Data Scientist Intern', 'DataTech Analytics', 'Exciting internship opportunity for aspiring data scientists. Work with real datasets and learn from industry experts.', 'Delhi, India', 'Internship', '$800 - $1,200/month', '0-1 years', ARRAY['Python', 'Pandas', 'NumPy', 'Scikit-learn', 'Jupyter'], '/placeholder-logo.png', 'active', '2024-01-25', '2024-02-25', 'https://datatech.com/internships/data-scientist', ARRAY['Currently pursuing degree in  '2024-01-25', '2024-02-25', 'https://datatech.com/internships/data-scientist', ARRAY['Currently pursuing degree in Computer Science or related field', 'Basic knowledge of Python and data analysis', 'Familiarity with machine learning concepts', 'Strong analytical and problem-solving skills']),
('Backend Developer', 'CloudTech Systems', 'We need an experienced Backend Developer to build scalable APIs and microservices for our cloud platform.', 'Hyderabad, India', 'Full-time', '$70,000 - $90,000', '3-5 years', ARRAY['Node.js', 'Express.js', 'PostgreSQL', 'Docker', 'AWS'], '/placeholder-logo.png', 'active', '2024-01-30', '2024-03-01', 'https://cloudtech.com/careers/backend', ARRAY['Strong experience with Node.js and databases', 'Knowledge of cloud platforms (AWS/Azure)', 'Experience with containerization', 'Understanding of microservices architecture']),
('Mobile App Developer', 'AppInnovate', 'Create amazing mobile experiences as part of our mobile development team. Work on both iOS and Android platforms.', 'Pune, India', 'Full-time', '$55,000 - $75,000', '2-4 years', ARRAY['React Native', 'Flutter', 'iOS', 'Android', 'Firebase'], '/placeholder-logo.png', 'active', '2024-02-01', '2024-03-01', 'https://appinnovate.com/jobs/mobile', ARRAY['Experience with React Native or Flutter', 'Knowledge of mobile app deployment', 'Understanding of mobile UI/UX principles', 'Experience with app store submissions']);

-- Insert sample communities
INSERT INTO communities (name, description, member_count, type, invite_link, status) VALUES
('Apna Coding Community', 'Join our vibrant community of developers, learners, and tech enthusiasts. Get help, share knowledge, and network with like-minded people.', 15000, 'discord', 'https://discord.gg/apnacoding', 'active'),
('Web Development Hub', 'A dedicated space for web developers to discuss latest trends, share resources, and collaborate on projects.', 8500, 'telegram', 'https://t.me/webdevhub', 'active'),
('AI & ML Enthusiasts', 'Connect with AI and Machine Learning practitioners, researchers, and enthusiasts. Share papers, discuss algorithms, and collaborate on projects.', 12000, 'discord', 'https://discord.gg/aiml', 'active'),
('Startup Founders Network', 'A WhatsApp community for startup founders to share experiences, seek advice, and find potential co-founders.', 3500, 'whatsapp', 'https://chat.whatsapp.com/startupfounders', 'active'),
('Open Source Contributors', 'Join fellow open source contributors to discuss projects, find collaborators, and share opportunities.', 6800, 'telegram', 'https://t.me/opensource', 'active');
