-- Insert sample courses
INSERT INTO courses (title, description, category, level, duration, instructor, students_count, rating, price, original_price, technologies, tags, redirect_url, status) VALUES
('Social Media Video Editing with Canva - From Beginner to Pro', 'Master Canva for creating stunning social media videos and graphics', 'Design & Video', 'Beginner', '8 hours', 'Udemy Expert', 15420, 4.8, 0, '$89.99', ARRAY['Canva', 'Video Editing'], ARRAY['Canva', 'Video Editing', 'Social Media'], 'https://techlinks.in/udemy-free-coupons/20519/social-media-video-editing-with-canva-from-beginner-to-pro', 'active'),
('Business Analyst Using Excel', 'Complete guide to business analysis using Microsoft Excel', 'Business & Finance', 'Intermediate', '12 hours', 'Udemy Expert', 8930, 4.7, 0, '$129.99', ARRAY['Excel', 'Business Analysis'], ARRAY['Excel', 'Business Analysis', 'Data Analysis'], 'https://techlinks.in/udemy-free-coupons/3472/business-analyst-using-excel', 'active'),
('AI Engineering Complete Bootcamp Masterclass', 'Complete AI engineering bootcamp from basics to advanced', 'Data Science & AI', 'Advanced', '25 hours', 'Udemy Expert', 18750, 4.9, 0, '$299.99', ARRAY['AI', 'Machine Learning'], ARRAY['AI', 'Machine Learning', 'Engineering'], 'https://techlinks.in/udemy-free-coupons/27226/ai-engineering-complete-bootcamp-masterclass', 'active'),
('Complete WordPress Elementor Guide - Design, Build & Earn', 'Master WordPress and Elementor for web design and development', 'Web Development', 'Beginner', '15 hours', 'Udemy Expert', 14560, 4.9, 0, '$199.99', ARRAY['WordPress', 'Elementor'], ARRAY['WordPress', 'Elementor', 'Web Design'], 'https://techlinks.in/udemy-free-coupons/26895/complete-wordpress-elementor-guide-design-build-earn', 'active'),
('The Complete Microsoft Excel Course - Basics to Programming', 'Master Excel from basics to advanced programming with VBA', 'Programming & Tech', 'Advanced', '18 hours', 'Udemy Expert', 19870, 4.9, 0, '$249.99', ARRAY['Excel', 'VBA'], ARRAY['Excel', 'VBA', 'Data Analysis'], 'https://techlinks.in/udemy-free-coupons/26872/the-complete-microsoft-excel-course-basics-to-programming', 'active');

-- Insert sample hackathons
INSERT INTO hackathons (title, description, start_date, end_date, location, prize_pool, participants_count, status, technologies, registration_link, whatsapp_link, organizer, partnerships, featured, mode, difficulty, max_team_size, registration_open) VALUES
('BNB AI Hack | Mumbai Edition', 'Build innovative AI solutions using BNB Chain technology. Join developers from across India for this exciting hackathon.', '2024-03-15 10:00:00+00', '2024-03-17 18:00:00+00', 'Mumbai, India', '₹5,00,000', 2500, 'upcoming', ARRAY['AI', 'Blockchain', 'BNB Chain', 'Machine Learning'], 'https://bnbhack-mumbai.devfolio.co/', 'https://chat.whatsapp.com/bnb-mumbai', 'BNB Chain', ARRAY['Devfolio', 'BNB Chain', 'Polygon'], true, 'offline', 'intermediate', 4, true),
('Smart India Hackathon 2024', 'National level hackathon to solve real-world problems using technology', '2024-04-20 09:00:00+00', '2024-04-22 17:00:00+00', 'New Delhi, India', '₹10,00,000', 5000, 'upcoming', ARRAY['Web Development', 'Mobile Apps', 'AI', 'IoT'], 'https://sih.gov.in/register', 'https://chat.whatsapp.com/sih-2024', 'Government of India', ARRAY['AICTE', 'Ministry of Education'], false, 'hybrid', 'intermediate', 6, true),
('Google Solution Challenge 2024', 'Build solutions for UN Sustainable Development Goals using Google technologies', '2024-05-10 00:00:00+00', '2024-05-12 23:59:00+00', 'Online', '$50,000', 3000, 'upcoming', ARRAY['Google Cloud', 'Firebase', 'Flutter', 'TensorFlow'], 'https://developers.google.com/community/gdsc-solution-challenge', 'https://chat.whatsapp.com/google-solution', 'Google', ARRAY['Google for Developers', 'GDSC'], false, 'online', 'advanced', 4, true),
('Microsoft Imagine Cup 2024', 'Global student technology competition to create innovative solutions', '2024-06-01 10:00:00+00', '2024-06-03 18:00:00+00', 'Bangalore, India', '$100,000', 1500, 'upcoming', ARRAY['Azure', 'AI', 'Mixed Reality', 'IoT'], 'https://imaginecup.microsoft.com/', 'https://chat.whatsapp.com/imagine-cup', 'Microsoft', ARRAY['Microsoft', 'Azure'], false, 'hybrid', 'advanced', 3, true),
('ETH India 2024', 'India\'s largest Ethereum hackathon bringing together developers, designers, and entrepreneurs', '2024-07-15 09:00:00+00', '2024-07-17 20:00:00+00', 'Bangalore, India', '$200,000', 4000, 'upcoming', ARRAY['Ethereum', 'Solidity', 'Web3', 'DeFi'], 'https://ethindia.co/register', 'https://chat.whatsapp.com/eth-india', 'ETH India', ARRAY['Ethereum Foundation', 'Polygon', 'Devfolio'], false, 'offline', 'advanced', 4, true);

-- Insert sample jobs
INSERT INTO jobs (title, company, description, location, type, salary, experience, technologies, status, apply_link, requirements) VALUES
('Senior Full Stack Developer', 'TechCorp', 'Join our team to build scalable web applications using React, Node.js, and cloud technologies. Work with cutting-edge tools and collaborate with talented engineers.', 'San Francisco, CA', 'Full-time', '$120k - $160k', 'Senior Level', ARRAY['React', 'Node.js', 'AWS', 'TypeScript'], 'active', 'https://techcorp.com/careers', ARRAY['5+ years experience', 'React/Node.js', 'AWS/GCP', 'Team leadership']),
('Frontend Developer', 'StartupXYZ', 'Build beautiful and responsive user interfaces for our SaaS platform. Create engaging user experiences with modern frontend technologies.', 'Remote', 'Full-time', '$80k - $110k', 'Mid Level', ARRAY['React', 'Vue.js', 'TypeScript', 'CSS'], 'active', 'https://startupxyz.com/jobs', ARRAY['3+ years experience', 'React/Vue.js', 'TypeScript', 'CSS/SCSS']),
('Data Scientist', 'DataCorp', 'Analyze large datasets and build machine learning models to drive business insights. Work with advanced analytics and AI technologies.', 'New York, NY', 'Full-time', '$100k - $130k', 'Mid Level', ARRAY['Python', 'Machine Learning', 'SQL', 'TensorFlow'], 'active', 'https://datacorp.com/careers', ARRAY['Python/R', 'Machine Learning', 'SQL', 'Statistics']),
('DevOps Engineer', 'CloudTech', 'Manage cloud infrastructure and implement CI/CD pipelines for our microservices architecture. Ensure scalability and reliability of our systems.', 'Austin, TX', 'Full-time', '$110k - $140k', 'Senior Level', ARRAY['AWS', 'Docker', 'Kubernetes', 'Terraform'], 'active', 'https://cloudtech.com/jobs', ARRAY['AWS/Azure', 'Docker/Kubernetes', 'Terraform', 'CI/CD']),
('Software Engineering Intern', 'BigTech', 'Summer internship program for computer science students to work on real projects. Gain hands-on experience with industry-leading technologies.', 'Seattle, WA', 'Internship', '$6k - $8k/month', 'Entry Level', ARRAY['Programming', 'Algorithms', 'Data Structures'], 'active', 'https://bigtech.com/internships', ARRAY['CS student', 'Programming skills', 'Problem solving', 'Team collaboration']);

-- Insert sample communities
INSERT INTO communities (name, description, member_count, type, invite_link, status) VALUES
('Apna Coding Discord', 'Main community for developers to discuss coding, share resources, and collaborate', 15000, 'discord', 'https://discord.gg/apnacoding', 'active'),
('Hackathon Updates', 'Get latest updates about hackathons and coding competitions', 8500, 'telegram', 'https://t.me/hackathonupdates', 'active'),
('Web Dev Community', 'WhatsApp group for web developers to share tips and resources', 2500, 'whatsapp', 'https://chat.whatsapp.com/webdev', 'active');

-- Create admin user (this will be handled by the auth system, but we can set up the role)
-- The actual user creation happens through Supabase Auth
